### ISSUE TITLE
Library creation

### ISSUE THREAD

**Issue by Neil-Ciciglycerin** [Nik300/InterpretLayer#2]
How would one create their own system library, so that it would work well with say, an implementation of some widgets, such as buttons, or allow for filesystem access?

**Comment by Nik300** [comment]
Hi Neil!
There’s unfortunately no way, I have abandoned the project a few years back
due to personal issues, plus I’ve never even believed the project had any
potential at all. To be honest your message brought the project back to my
attention.
As of now tho the project is nothing more than a proof of concept, I’ll dig
right back into it in the following days. If you want to implement your own
way to use a custom system library, please do!

**Comment by Neil-Ciciglycerin** [comment]
Ok! I personally believe this has lots of potential! I think you might be able to make your own library by poking into the source code and implementing it in the same way you implemented the system library. I hope to see this improve over time!
